//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FARecurringCost
    {
        public int Id { get; set; }
        public string CostCode { get; set; }
        public string CostDesc { get; set; }
        public Nullable<int> Amortized { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
