//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FixedAsset
    {
        public int Id { get; set; }
        public string CatCode { get; set; }
        public string ClassCode { get; set; }
        public string FACode { get; set; }
        public string FAName { get; set; }
        public Nullable<int> DepMethod { get; set; }
        public Nullable<decimal> Deprate { get; set; }
        public Nullable<int> LifeSpan { get; set; }
        public string LocationCode { get; set; }
        public byte[] PurchaseDate { get; set; }
        public Nullable<decimal> FACost { get; set; }
        public Nullable<decimal> ResidualVal { get; set; }
        public Nullable<decimal> AccumDep { get; set; }
        public Nullable<int> LifeSpanUsed { get; set; }
        public Nullable<System.DateTime> DepStartDate { get; set; }
        public string FAGLAccount { get; set; }
        public string FundingGL { get; set; }
        public string AccumDepGL { get; set; }
        public string ExpenseGL { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DisposalMethod { get; set; }
        public Nullable<decimal> DisposalAmt { get; set; }
        public string UserID { get; set; }
        public string AuthID { get; set; }
    }
}
