//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FARecuringAmortSchedule
    {
        public int Id { get; set; }
        public string FACode { get; set; }
        public string CostCode { get; set; }
        public Nullable<decimal> MonthlyRunRate { get; set; }
        public Nullable<System.DateTime> NextAmortDate { get; set; }
        public Nullable<int> Tenor { get; set; }
        public Nullable<int> TenorSpent { get; set; }
        public Nullable<int> status { get; set; }
    }
}
