//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FARecurringClass
    {
        public int Id { get; set; }
        public string ClassCode { get; set; }
        public string CostCode { get; set; }
        public Nullable<int> status { get; set; }
        public string UserID { get; set; }
        public string AuthID { get; set; }
    }
}
