//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FADepSchedule
    {
        public int Id { get; set; }
        public string AssetCode { get; set; }
        public Nullable<int> Installment { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> YearlyDep { get; set; }
        public Nullable<decimal> MonthlyDep { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
