//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FALocation
    {
        public int Id { get; set; }
        public string FACode { get; set; }
        public string FALocationCode { get; set; }
        public byte[] DateAllocated { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ReceiptStatus { get; set; }
        public string UserID { get; set; }
        public string AuthID { get; set; }
        public string ReceiptBy { get; set; }
        public string AssetGL { get; set; }
        public string AccumDepGL { get; set; }
        public string DepExpenseGL { get; set; }
    }
}
