//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branch
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string address2 { get; set; }
        public string Address3 { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> status { get; set; }
        public string cashaccount { get; set; }
        public string suspenseDR { get; set; }
        public string suspenseCR { get; set; }
        public string InterBranchGL { get; set; }
        public Nullable<int> BranchType { get; set; }
        public string MBranchCode { get; set; }
        public string SBranchCode { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> create_dt { get; set; }
        public string region { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string authid { get; set; }
        public Nullable<int> subbranch { get; set; }
    }
}
