//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FAMaintenaceHist
    {
        public int Id { get; set; }
        public string FACode { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> Tranamount { get; set; }
        public byte[] TranDate { get; set; }
        public Nullable<int> expMethod { get; set; }
        public string DRGL { get; set; }
        public string CRGL { get; set; }
        public Nullable<int> MaintType { get; set; }
        public Nullable<int> status { get; set; }
        public string UserID { get; set; }
        public string AuthID { get; set; }
    }
}
