//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FARecurringgCostTrans
    {
        public int Id { get; set; }
        public string FACode { get; set; }
        public string CostCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public byte[] TranDate { get; set; }
        public string Narration { get; set; }
        public Nullable<int> ExpMethod { get; set; }
        public string DRAccount { get; set; }
        public string CRAccount { get; set; }
        public Nullable<decimal> MonthlyRunRate { get; set; }
        public Nullable<System.DateTime> NextAmortDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string UserID { get; set; }
        public string AuthID { get; set; }
    }
}
