//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixedAsset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Role
    {
        public int role_id { get; set; }
        public string role_name { get; set; }
        public string roledesc { get; set; }
        public Nullable<int> access_days { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> isoperation { get; set; }
        public Nullable<int> reqLimit { get; set; }
        public Nullable<int> status { get; set; }
        public string authid { get; set; }
        public string userid { get; set; }
        public Nullable<bool> canauth { get; set; }
        public Nullable<int> role_level { get; set; }
        public Nullable<bool> Commitee { get; set; }
    }
}
